// "use client";

import NavBar from "./components/NavBar";
import "./globals.css";

import QueryProvider from "./provider";

// import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
// const queryClient = new QueryClient();

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <QueryProvider>
        <body className="w-screen h-screen flex flex-col">
          <NavBar />
          <div className="w-full h-full p-10 bg-slate-300 flex overflow-auto">
            <div className="w-full h-full bg-white rounded flex">
              {children}
            </div>
          </div>
        </body>
      </QueryProvider>
    </html>
  );
}

// shared layout must be in body here...
