import NavBar from "./components/NavBar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-screen h-screen bg-slate-500 flex flex-col">
        <NavBar />
        <div className="w-full h-full p-10">
          <div className="w-full h-full bg-white rounded">{children}</div>
        </div>
      </body>
    </html>
  );
}

// shared layout must be in body here...
